Revert "raphael: Move to new linker flag"
fixes some Kernel compilation errors while buildiing roms such as ,

clang-14: error: unable to execute command: Executable "ld" doesn't exist!
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [scripts/Makefile.host:90: scripts/basic/fixdep] Error 1
ld.lld: error: undefined symbol

This reverts commit 3b260934f8b11f40cdb99b7d232a2f143f1c73f9.

Signed-off-by: SageOfD6Path <mail2anirban95@gmail.com>